name: Pulumi Infra

on:
  pull_request:
  push:
    branches: [ main ]
  
permissions:
  id-token: write
  actions: read
  contents: read
  issues: write
  pull-requests: write

jobs:
  pulumi:
    name: Pulumi ${{ github.event_name == 'pull_request' && 'preview' || 'up' }}
    timeout-minutes: 30
    runs-on: ubuntu-latest
    environment: ${{ github.event_name == 'pull_request' && 'preview' || 'infra' }}
    env:
      WORK_DIR: ./src/BadBort.AzureRm.Foundation.Infra
      PULUMI_STACK: adi-tenant
    steps:
      - name: Serialize workflow runs
        uses: jsok/serialize-workflow-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - run: |
          echo "backend container name: ${{vars.BACKEND_CONTAINER_NAME}}"
          
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x

      - uses: azure/login@v2
        name: Azure OIDC login
        with:
          allow-no-subscriptions: true
          client-id: ${{ vars.AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }} 
          
      - name: Pulumi refresh
        uses: pulumi/actions@v6
        with:
          command: refresh
          work-dir: ${{ env.WORK_DIR }}
          stack-name: ${{ env.PULUMI_STACK }}
          cloud-url: azblob://${{vars.BACKEND_CONTAINER_NAME }}?storage_account=${{vars.BACKEND_STORAGE_ACCOUNT }}
          secrets-provider: azurekeyvault://kv-badbort-pulumi-pw.vault.azure.net/keys/infra-azure-foundations-stack-adi-tenant
          config-map: |
            data_dir: 
              value: ${{ github.workspace }}/data
            tenant: 
              value: adi

      - name: Pulumi deploy
        uses: pulumi/actions@v6
        with:
          command: ${{ github.event_name == 'pull_request' && 'preview' || 'up' }}
          work-dir: ${{ env.WORK_DIR }}
          stack-name: ${{ env.PULUMI_STACK }}
          cloud-url: azblob://${{vars.BACKEND_CONTAINER_NAME }}?storage_account=${{vars.BACKEND_STORAGE_ACCOUNT }}
          secrets-provider: azurekeyvault://kv-badbort-pulumi-pw.vault.azure.net/keys/infra-azure-foundations-stack-adi-tenant
          config-map: |
            data_dir: 
              value: ${{ github.workspace }}/data
            tenant: 
              value: adi
          comment-on-pr: true
          comment-on-summary: true
          always-include-summary: true
          diff: true
          upsert: true
